# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

bioc_required: true
bioc_use_devel: true

bioc_packages:
- rhdf5

before_install:
  - export RGL_USE_NULL=TRUE

#install:
#  - ./travis-tool.sh bioc_install rhdf5
#  - ./travis-tool.sh install_bioc_deps

r_github_packages:
  - marionlouveaux/mamut2r  # pre-install to avoid vignette package errors

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
