# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

bioc_required: true
bioc_use_devel: true

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --yes --force-yes update -qq; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --yes libudunits2-dev; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install udunits; fi;
  - export RGL_USE_NULL=TRUE

bioc_packages:
  - rhdf5

r_packages:
  - classInt
  - dplyr
  - ggplot2
  - ggraph
  - glue
  - grDevices
  - igraph
  - magrittr
  - purrr
  - stats
  - tibble
  - utils
  - viridis
  - xml2
  - cowplot
  - knitr
  - pkgdown
  - rmarkdown
  - XML
#
#
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --yes --force-yes update -qq; fi;
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable; fi;
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi;
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev; fi;
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e "install.packages(c('sp', 'devtools'))"; fi;
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install Caskroom/cask/xquartz; fi;
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ghostscript; fi;
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages(c('rgdal','rgeos','RandomFieldsUtils','RandomFields'))"; fi;
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages('digest', type = 'source')"; fi;
#- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr update --self; fi;

#install:
#  - ./travis-tool.sh bioc_install rhdf5
#  - ./travis-tool.sh install_bioc_deps

r_github_packages:
  - marionlouveaux/mamut2r  # pre-install to avoid vignette package errors

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
